In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import xgboost as xgb
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestRegressor


# Load the saved dataset
final_df = pd.read_csv('final_gold_price_dataset.csv')

In [2]:
# Load the saved dataset
final_df = pd.read_csv('final_gold_price_dataset.csv')

final_df.fillna(0, inplace=True)
final_df

,momentum_gold,high_low_gold,close_gold,daily_percent_change_gold,food_beverages_tobacco_return,non_banking_financial_return,real_estate_return,banks_return,basic_resources_return,energy_support_services_return,...,EFFR_std 30,housing_index,house_pct_change,house_volt,oil_WTI,oil_EURO,oil_WTI_pctChange,oil_WTI_volt,oil_EURO_pctChange,oil_Euro_volt
0,0.0,0.000000,775.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,212.398,0.0,0.000000,61.17,67.05,0.000000,0.000000,0.000000,0.000000
1,0.0,0.000000,776.0,0.129032,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,212.398,0.0,0.000000,61.17,67.05,0.000000,0.000000,0.000000,0.000000
2,-1.0,0.381679,786.0,1.288660,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,212.398,0.0,0.000000,63.00,69.08,0.029917,0.000000,0.030276,0.000000
3,0.0,0.000000,791.0,0.636132,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,212.398,0.0,0.000000,63.00,69.08,0.000000,0.000000,0.000000,0.000000
4,0.0,0.000000,792.0,0.126422,-0.026247,-0.044436,-0.070660,-0.022724,-0.072285,-0.087912,...,0.0,212.398,0.0,0.000000,63.00,69.08,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,34.0,2.215453,3691.0,-3.021545,0.037209,0.017516,-0.007184,0.006051,0.044271,0.056503,...,0.0,310.847,0.0,0.351203,74.31,80.97,-0.020174,0.953767,0.009223,0.624076
1457,-69.0,2.265647,3531.0,-4.334869,0.048954,0.013041,-0.005499,0.024716,0.005046,-0.007064,...,0.0,310.847,0.0,0.292018,72.02,79.04,-0.030817,0.978227,-0.023836,0.588094
1458,0.0,0.000000,3577.0,1.302747,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,310.847,0.0,0.210143,71.89,77.69,-0.001805,1.116809,-0.017080,1.008837
1459,-46.0,1.265823,3634.0,1.593514,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,310.847,0.0,0.000000,71.89,77.69,0.000000,1.209307,0.000000,1.182596
1460,0.0,0.000000,3634.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000,0.0,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000

In [3]:

# Load the target data
target_df = pd.read_csv(r'C:\\Users\\youss\\OneDrive - aucegypt.edu\\Desktop\\Hackathon\\train data\\train data\\target_gold.csv')

# Drop the 'date' column from the target data
target_df = target_df.drop(columns=['date'])

In [4]:
target_df

      pct_change
0       0.129032
1       1.288660
2       0.636132
3       0.126422
4       1.262626
...          ...
1456   -4.334869
1457    1.302747
1458    1.593514
1459    0.000000
1460    0.935608

[1461 rows x 1 columns]

In [5]:
# Merge the feature dataset and target dataset
# Assuming the target column in 'target_df' is named 'target_column'
X = final_df  # Feature set
y = target_df['pct_change']  # Target set

In [6]:
X

,momentum_gold,high_low_gold,close_gold,daily_percent_change_gold,food_beverages_tobacco_return,non_banking_financial_return,real_estate_return,banks_return,basic_resources_return,energy_support_services_return,...,EFFR_std 30,housing_index,house_pct_change,house_volt,oil_WTI,oil_EURO,oil_WTI_pctChange,oil_WTI_volt,oil_EURO_pctChange,oil_Euro_volt
0,0.0,0.000000,775.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,212.398,0.0,0.000000,61.17,67.05,0.000000,0.000000,0.000000,0.000000
1,0.0,0.000000,776.0,0.129032,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,212.398,0.0,0.000000,61.17,67.05,0.000000,0.000000,0.000000,0.000000
2,-1.0,0.381679,786.0,1.288660,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,212.398,0.0,0.000000,63.00,69.08,0.029917,0.000000,0.030276,0.000000
3,0.0,0.000000,791.0,0.636132,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,212.398,0.0,0.000000,63.00,69.08,0.000000,0.000000,0.000000,0.000000
4,0.0,0.000000,792.0,0.126422,-0.026247,-0.044436,-0.070660,-0.022724,-0.072285,-0.087912,...,0.0,212.398,0.0,0.000000,63.00,69.08,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,34.0,2.215453,3691.0,-3.021545,0.037209,0.017516,-0.007184,0.006051,0.044271,0.056503,...,0.0,310.847,0.0,0.351203,74.31,80.97,-0.020174,0.953767,0.009223,0.624076
1457,-69.0,2.265647,3531.0,-4.334869,0.048954,0.013041,-0.005499,0.024716,0.005046,-0.007064,...,0.0,310.847,0.0,0.292018,72.02,79.04,-0.030817,0.978227,-0.023836,0.588094
1458,0.0,0.000000,3577.0,1.302747,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,310.847,0.0,0.210143,71.89,77.69,-0.001805,1.116809,-0.017080,1.008837
1459,-46.0,1.265823,3634.0,1.593514,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,310.847,0.0,0.000000,71.89,77.69,0.000000,1.209307,0.000000,1.182596
1460,0.0,0.000000,3634.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000,0.0,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000

In [7]:
# Initialize MinMaxScaler to scale between 0 and 1
scaler = MinMaxScaler(feature_range=(-1, 1))

# Apply MinMaxScaler to the entire dataset
X_scaled = scaler.fit_transform(X)  # X is your features DataFrame

# Assuming X_scaled is the array after scaling, and X is the original DataFrame with the column names
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

top_10_features =[
    'gold_voltality_30', 'gold_voltality_7', 'food_beverages_tobacco_volume', 
    'real_estate_volume', 'daily_percent_change_gold_trend', 'banks_return', 
    'vxeem_close', 'basic_resources_return', 'house_volt', 'basic_resources_volume', 
    'oil_WTI_pctChange', 'oil_EURO_pctChange', 'vxeem_avg_7', 'market_proxy', 
    'daily_percent_change_gold', 'energy_support_services_volume', 
    'non_banking_financial_volume', 'basic_resources_return', 'vix_close_pctChange', 
    'news_title', 'food_beverages_tobacco_return', 'energy_support_services_return', 
    'tag_egyptian_stock_exchange',  'inflation_month_core', 
    'oil_Euro_volt', 'non_banking_financial_return', 'energy_support_services_return', 
    'vxeem_close_pctChange', 'inflation_year_Core', 'inflation_year_headline', 
    'tag_geopolitical_tensions', 'EFFR_std 30', 'EFFR_pctChange', 'Overnight Deposit Rate', 
    'house_pct_change'
]

In [8]:
from scipy import stats
import numpy as np

corr_matrix = X_scaled_df.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
to_drop = [column for column in upper.columns if any(upper[column] > 0.9)]
X_scaled_df = X_scaled_df.drop(to_drop, axis=1)

to_drop

['high_low_gold',
 'tag_egyptian_stock_exchange',
 'inflation_month_core',
 'inflation_year_headline',
 'inflation_year_Core',
 'Overnight Deposit Rate',
 'Overnight Lending Rate',
 'std change Lending Rate 30',
 'vix_avg_7',
 'vxeem_close',
 'vxeem_avg_7',
 'EFFR',
 'oil_EURO']

In [9]:
# Splitting the dataset into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X_scaled_df, y, test_size=0.2, random_state=42)

X_train = X_train[top_10_features]

X_val = X_val[top_10_features]

print("Shape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)

In [10]:
# Check if X_train and X_val are Pandas DataFrames, convert them to NumPy arrays if necessary
X_train_np = X_train.to_numpy() if isinstance(X_train, pd.DataFrame) else X_train
X_val_np = X_val.to_numpy() if isinstance(X_val, pd.DataFrame) else X_val

# Ensure that all features are numeric
print(X_train_np.dtype)
print(X_val_np.dtype)


# Convert to DMatrix for XGBoost
train_dmatrix = xgb.DMatrix(X_train_np, label=y_train)
val_dmatrix = xgb.DMatrix(X_val_np, label=y_val)

float64
float64

In [13]:

from sklearn.model_selection import GridSearchCV

param_grid = {
   
    'max_depth': [7],
    'learning_rate': [0.01],
    'subsample': [1.0],
    'colsample_bytree': [0.8],
    'reg_alpha': [0.1],  # L1 regularization
    'reg_lambda': [100.0],  # L2 regularization
    'min_child_weight': 5,  # Minimum sum of instance weight in a leaf
    'gamma': 0.5  
}

# Pass the params to GridSearchCV
grid_search = GridSearchCV(estimator=xgb.XGBRegressor(), param_grid=param_grid, scoring='neg_mean_squared_error', cv=3, n_jobs=-1, verbose=2)

# Train the model using the best combination of parameters
grid_search.fit(X_train, y_train)

# Retrieve the best parameters found by GridSearchCV
print(grid_search.best_params_)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
{'colsample_bytree': 0.8, 'gamma': 0.5, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 5, 'reg_alpha': 0.1, 'reg_lambda': 100.0, 'subsample': 1.0}

In [18]:
# Set the hyperparameters for XGBoost
params = {

    'max_depth': 12,
    'learning_rate': 0.01,
    'subsample': 1.0,
    'colsample_bytree': 0.8,
    'reg_alpha': 0.1,  # L1 regularization
    'reg_lambda': 200,  # L2 regularization
    'min_child_weight': 5,  # Minimum sum of instance weight in a leaf
    'gamma': 0.5                      # L1 regularization term           
}

In [ ]:

# Train the model using XGBoost's train function
xgb_model = xgb.train(params, train_dmatrix, num_boost_round=100000)

In [ ]:
## Convert X_train and X_val to DMatrix
from sklearn.metrics import mean_squared_error  # Import this to calculate RMSE
# Check if X_train and X_val are Pandas DataFrames, convert them to NumPy arrays if necessary
X_train_np = X_train.to_numpy() if isinstance(X_train, pd.DataFrame) else X_train
X_val_np = X_val.to_numpy() if isinstance(X_val, pd.DataFrame) else X_val

# Ensure that all f


train_dmatrix = xgb.DMatrix(X_train_np, label=y_train)
val_dmatrix = xgb.DMatrix(X_val_np, label=y_val)

# Predict on the training set
y_train_pred = xgb_model.predict(train_dmatrix)

# Predict on the validation set
y_val_pred = xgb_model.predict(val_dmatrix)

# Calculate RMSE on the training set
train_rmse = mean_squared_error(y_train, y_train_pred, squared=False)
print(f"Training RMSE: {train_rmse}")

# Calculate RMSE on the validation set
val_rmse = mean_squared_error(y_val, y_val_pred, squared=False)
print(f"Validation RMSE: {val_rmse}")

In [ ]:
import numpy as np

# Mean Directional Accuracy (MDA)
def mean_directional_accuracy(y_true, y_pred):
    # Ensure y_true is a NumPy array
    if isinstance(y_true, pd.DataFrame) or isinstance(y_true, pd.Series):
        y_true = y_true.values  # Convert to NumPy array if it's a DataFrame or Series
    
    # Ensure both arrays have the same length after shifting
    y_true_diff = np.sign(y_true[1:] - y_true[:-1])
    y_pred_diff = np.sign(y_pred[1:] - y_pred[:-1])
    return np.mean(y_true_diff == y_pred_diff)

# Convert y_val to NumPy array if it is a DataFrame or Series
y_val_np = y_val.values if isinstance(y_val, pd.DataFrame) else y_val

# Calculate MDA
mda = mean_directional_accuracy(y_val_np, y_val_pred)
print(f"Mean Directional Accuracy: {mda}")

from xgboost import plot_importance
import matplotlib.pyplot as plt

# Plot feature importance
plot_importance(xgb_model)  # 'weight', 'gain', or 'cover'
plt.show()

In [17]:
import pickle
import os
# Define the path where you want to save the model (replace this with your desired path)
save_directory = "C:\\Users\\youss\\OneDrive - aucegypt.edu\\Desktop\\beltone_3\\Pickles"



# Save the trained model to a pickle file in the specified directory
with open(os.path.join(save_directory, 'xgb_model_4.pkl'), 'wb') as model_file:
    pickle.dump(xgb_model, model_file)